### PR TITLE
Condensing If/Else If statements

### PR DESCRIPTION
**Pull request by jwd11**
Hi, I just shortened the if/else if statements into one if statement with a bunch of or cases on line 59. I know nothing about js but its similar enough to c so dont bother asking me questions n shit.

### CODE REVIEW

**Comment by jwd11** [comment]
Yessir

**Comment by huysuh** [comment]
who the FUCK are you

**Review by huysuh — COMMENTED** [review]
looks good.i approve.

**Comment by ilylol123** [comment]
op

**Pull request merged**
